#my Data
my:
 data:
  name: suresh
  desg: IT-software
   
#address
  address:
  hno: 3-123
  colony: bustand area
  city: hyd
  pin: 500524
#contact 
  contact:
   mobNo1: 9012458
   mobNo2: 8012458
   landLineNo: 040215354
   
   
   
emp:
  info:
    comp-details:
      location: hyd
      size: 200
      title: HCL Technologies
    id: 1001
    id-details:
      adharNo: 534545555345454353
      panNo: AJXPR354566
      voterId: 553545677666666
    name: rajesh
    nick-names:
    - chinna
    - kanna
    - munna
    phone-numbers:
    - 88888888888
    - 77777777777
    - 667777777777
    
    team-members:
    - ravi
    - srinu
    - ravi