spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:oracle:thin:@localhost:1521:suri
    username: system
